(function(){
'use strict';
const defaults={products:[{id:'naka',name:'Combinado Naka',price:129,description:'32 peças entre sushis, sashimis e rolls. Nossa seleção para dois.',details:'32 PEÇAS · SERVE 2 PESSOAS',badge:'PARA COMPARTILHAR',category:'combinados',image:'combinado'},{id:'roll',name:'Roll especial da casa',price:42,description:'Salmão, cream cheese, toque crocante e finalização com ovas.',details:'8 PEÇAS · FEITO NA HORA',badge:'O QUERIDINHO DA CASA',category:'rolls',image:'rolls'},{id:'teishoku',name:'Teishoku de salmão',price:68,description:'Salmão grelhado, gohan, legumes da estação e missoshiru.',details:'PRATO INDIVIDUAL · SERVE 1 PESSOA',badge:'CONFORTO JAPONÊS',category:'quentes',image:'teishoku'}],contact:{address:'Rua das Cerejeiras, 128 · Santa Tereza\nBelo Horizonte, MG',hours:'Terça a quinta · 18h às 23h\nSexta e sábado · 18h à meia-noite\nDomingo · 12h às 22h',phone:'(31) 3333-0128',email:'oi@sushinaka.example'}};
const categories=['combinados','rolls','quentes'];const images=['combinado','rolls','teishoku','sashimi'];let connection;
const siteRoot=new URL('.',document.currentScript.src);
function valid(data){return data&&Array.isArray(data.products)&&data.products.every(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&Number.isFinite(p.price)&&p.price>=0&&categories.includes(p.category)&&images.includes(p.image)&&(!p.photo||(typeof p.photo==='string'&&p.photo.length<2000000&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p.photo)))&&['description','details','badge'].every(k=>typeof p[k]==='string'))&&data.contact&&['address','hours','phone','email'].every(k=>typeof data.contact[k]==='string')}
function open(){if(!connection)connection=new Promise((resolve,reject)=>{if(!window.indexedDB){reject(new Error('Banco local indisponível neste navegador.'));return;}const req=indexedDB.open('sushi-naka-local',1);req.onupgradeneeded=()=>req.result.createObjectStore('content');req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('Feche outras abas do painel e tente novamente.'));req.onsuccess=()=>{const db=req.result;db.onversionchange=()=>{db.close();connection=null};resolve(db)}}).catch(e=>{connection=null;throw e});return connection}
async function read(){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('content','readwrite');const store=tx.objectStore('content');const req=store.get('site');let data;req.onsuccess=()=>{data=req.result;if(!data){data=structuredClone(defaults);store.put(data,'site')}else if(!valid(data)){tx.abort();}};tx.oncomplete=()=>resolve(data);tx.onerror=()=>reject(tx.error||new Error('Não foi possível ler o banco local.'));tx.onabort=()=>reject(new Error('Não foi possível ler o banco local.'))})}
async function update(change){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('content','readwrite');const store=tx.objectStore('content');const req=store.get('site');let data;req.onsuccess=()=>{try{data=req.result||structuredClone(defaults);change(data);if(!valid(data))throw new Error('Dados inválidos.');store.put(data,'site')}catch(e){tx.abort()}};tx.oncomplete=()=>{resolve(data)};tx.onerror=()=>reject(tx.error||new Error('Não foi possível salvar.'));tx.onabort=()=>reject(new Error('Não foi possível salvar. Confira os dados e tente novamente.'))})}
function photoSource(product){return product.photo||new URL('assets/'+product.image+'.webp',siteRoot).href}
window.NakaDB={read,update,defaults,categories,images,photoSource};
})();
