(function(){
'use strict';
const list=document.querySelector('#product-list'),status=document.querySelector('#status'),editor=document.querySelector('#product-dialog'),form=document.querySelector('#product-form'),contactForm=document.querySelector('#contact-form'),deleteDialog=document.querySelector('#delete-dialog');let state,editingId=null,deletingId=null,pendingPhoto=null,photoLoading=false,photoRequest=0;
const upload=document.querySelector('#photo-upload'),preview=document.querySelector('#photo-preview'),photoStatus=document.querySelector('#photo-status'),useLibrary=document.querySelector('#use-library');
function updatePreview(){preview.src=pendingPhoto||'/assets/'+form.elements.namedItem('image').value+'.webp';useLibrary.hidden=!pendingPhoto}
function resetPhoto(){photoRequest++;photoLoading=false;pendingPhoto=null;upload.value='';photoStatus.textContent='';form.querySelector('[type=submit]').disabled=false;updatePreview()}
form.elements.namedItem('image').addEventListener('change',resetPhoto);useLibrary.onclick=resetPhoto;
editor.addEventListener('close',()=>{photoRequest++;photoLoading=false});
upload.addEventListener('change',async()=>{const file=upload.files[0];if(!file)return;const request=++photoRequest;photoLoading=true;form.querySelector('[type=submit]').disabled=true;photoStatus.textContent='Preparando a foto…';document.querySelector('#editor-error').textContent='';try{const photo=await NakaPhoto.prepare(file);if(request!==photoRequest)return;pendingPhoto=photo;updatePreview();photoStatus.textContent='Foto pronta. Salve o produto para aplicar.'}catch(e){if(request!==photoRequest)return;document.querySelector('#editor-error').textContent=e.message;photoStatus.textContent='';upload.value=''}finally{if(request===photoRequest){photoLoading=false;form.querySelector('[type=submit]').disabled=false}}});
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});const categoryNames={combinados:'Combinados',rolls:'Sushis & rolls',quentes:'Pratos quentes'};
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node}
function message(text,error=false){status.textContent=text;status.classList.toggle('error',error)}
function render(){list.replaceChildren();document.querySelector('#product-count').textContent=state.products.length+' produto'+(state.products.length===1?'':'s');for(const p of state.products){const row=el('div',undefined,'product-row'),img=el('img');img.src=NakaDB.photoSource(p);img.alt=p.name;const info=el('div');info.append(el('h3',p.name),el('p',categoryNames[p.category]));const actions=el('div',undefined,'row-actions');const edit=el('button','Editar','secondary');edit.type='button';edit.setAttribute('aria-label','Editar '+p.name);edit.onclick=()=>openEditor(p);const remove=el('button','Remover','secondary danger');remove.type='button';remove.setAttribute('aria-label','Remover '+p.name);remove.onclick=()=>{deletingId=p.id;document.querySelector('#delete-name').textContent=p.name;document.querySelector('#delete-error').textContent='';deleteDialog.showModal()};actions.append(edit,remove);row.append(img,info,el('strong',money.format(p.price)),actions);list.append(row)}if(!state.products.length)list.append(el('p','Nenhum produto cadastrado. Adicione o primeiro produto.'));}
function openEditor(product){form.reset();resetPhoto();editingId=product?.id||null;document.querySelector('#editor-title').textContent=product?'Editar produto':'Adicionar produto';document.querySelector('#editor-error').textContent='';if(product)for(const key of ['name','price','category','description','details','badge','image'])form.elements.namedItem(key).value=product[key];pendingPhoto=product?.photo||null;updatePreview();editor.showModal()}
document.querySelector('#new-product').onclick=()=>openEditor();document.querySelector('#product-dialog .close').onclick=()=>editor.close();document.querySelector('#cancel-delete').onclick=()=>deleteDialog.close();
form.onsubmit=async event=>{event.preventDefault();if(photoLoading)return;const save=form.querySelector('[type=submit]');save.disabled=true;document.querySelector('#editor-error').textContent='';const f=new FormData(form);const product={id:editingId||crypto.randomUUID(),name:String(f.get('name')).trim(),price:Number(f.get('price')),description:String(f.get('description')).trim(),details:String(f.get('details')).trim(),badge:String(f.get('badge')).trim(),category:f.get('category'),image:f.get('image')};if(pendingPhoto)product.photo=pendingPhoto;try{if(!product.name||!product.description)throw Error('Preencha o nome e a descrição.');state=await NakaDB.update(data=>{const index=data.products.findIndex(p=>p.id===product.id);if(index<0)data.products.push(product);else data.products[index]=product});render();editor.close();message('Produto salvo. A landing page já está atualizada neste navegador.')}catch(e){document.querySelector('#editor-error').textContent=e.message}finally{save.disabled=false}};
document.querySelector('#confirm-delete').onclick=async()=>{const button=document.querySelector('#confirm-delete');button.disabled=true;try{state=await NakaDB.update(data=>{data.products=data.products.filter(p=>p.id!==deletingId)});render();deleteDialog.close();message('Produto removido.')}catch(e){document.querySelector('#delete-error').textContent=e.message}finally{button.disabled=false}};
contactForm.onsubmit=async event=>{event.preventDefault();const button=contactForm.querySelector('button');button.disabled=true;const f=new FormData(contactForm);const contact=Object.fromEntries(['address','hours','phone','email'].map(k=>[k,String(f.get(k)).trim()]));try{if(Object.values(contact).some(v=>!v))throw Error('Preencha todos os contatos.');state=await NakaDB.update(data=>{data.contact=contact});message('Contatos salvos. A landing page já está atualizada neste navegador.')}catch(e){message(e.message,true)}finally{button.disabled=false}};
(async()=>{try{state=await NakaDB.read();render();for(const [key,value]of Object.entries(state.contact))contactForm.elements.namedItem(key).value=value;document.querySelector('#new-product').disabled=false;contactForm.querySelector('button').disabled=false;message('Banco local pronto.')}catch(e){message('Não foi possível abrir o banco local. Recarregue a página ou permita o armazenamento neste navegador.',true)}})();
})();
